FROM python:3.10-slim

# Instalamos dependencias del sistema requeridas por librosa (libsndfile1) y OpenCV (libgl1, libglib2.0-0)
RUN apt-get update && \
    apt-get install -y libsndfile1 libgl1 libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api/app.py .
COPY api/modelos_audio.py .
COPY modelos/ ./modelos/

EXPOSE 5000
CMD ["python", "app.py"]